---
- name: Stop Azure VMs
  hosts: localhost
  connection: local
  gather_facts: false
  roles:
    - teardown

# - name: Install Nodejs App
#   hosts: azure
#   become: yes
#   vars:
#     system_user: ansible
#   roles:
#     - zsh
#     - epel
#     - cic2

- name: Send Email with URL
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Send Email 
      sendgrid:
        api_key: "{{ vault_sendgrid_api_key }}"
        from_address: "user@cic3demo.com"
        to_addresses:
          - "bsollar@redhat.com"
          # - "{{ user_email }}"
        subject: "CloudForms Azure VM Monitoring"
        body: "Name	cic3-demo IP Addresses	10.0.0.6, 52.227.141.216
               Management Engine GUID	130d0ee2-a67b-4c35-89fa-e9e14afa2f91
               ID within Provider	f034aed9-13c2-4391-8d92-9a008b56b492\rg-cic3\microsoft.compute/virtualmachines\cic3-demo"
      delegate_to: localhost