# file: roles/sendgrid/tasks/main.yml
---
- sendgrid:
      api_key: "{{ vault_sendgrid_api_key }}"
      from_address: "admin@cic3demo.com"
      to_addresses:
        - "bsollar@redhat.com"
        - "{{ user_email }}"
      subject: "CIC3 metrics alerts"
      body: "System capacity alert"
  delegate_to: localhost
  # when: email == "ares"
  tags:
    - ares
  



